# Generated by Django 5.1.2 on 2026-01-09 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-\\.\\?]+$', 'Only alphanumeric characters, spaces, and basic punctuation are allowed.')]),
        ),
    ]
