# Generated by Django 5.1.15 on 2026-01-09 12:56

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('tasks', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Logging & Monitoring (Admin Actions)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Security Event', 'verbose_name_plural': 'Logging & Monitoring (Security)'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
